### ISSUE TITLE
how to make style marker only, and remove other toolbar

### ISSUE THREAD

**Issue by dwiwijaya** [alexantr/yii2-ckeditor#4]

**Comment by alexantr** [comment]
```
<?= alexantr\ckeditor\CKEditor::widget([
    'name' => 'attributeName',
    'clientOptions' => [
        'toolbar' => [
            ['BulletedList', '-', 'Outdent', 'Indent'],
        ],
    ],
]) ?>
```

**Comment by dwiwijaya** [comment]
how to make the input uneditable/cannot adding text but user only can add the marker to the text, isit possible? @alexantr

**Comment by alexantr** [comment]
@11Dwiwijaya it's CKeditor's job. Please read [documentation](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html).
